# Notebook de validation du pipeline RAG

Dans le présent notebook, nous allons:

- tester plusieurs requêtes en boucle,
- afficher les chunks utilisés,
- annoter manuellement la pertinence des réponses,
- stocker les résultats pour analyse ou feedback d'équipe.
- utiliser un framework spécialisé pour évaluer le système RAG => RAGAS

⚠️ **Note après migration OpenAI** : Ce notebook a été mis à jour pour utiliser les embeddings OpenAI. Pour éviter la lenteur, utilisez d'abord le test rapide, puis la boucle complète si nécessaire.

In [ ]:
# Imports et chargement du vectorstore + LLM (versions mises à jour)

from langchain_openai import ChatOpenAI, OpenAIEmbeddings # Pour interagir avec l'API OpenAI et générer des embeddings
from langchain_community.vectorstores import FAISS # Pour l'indexation FAISS
import os # Pour les opérations sur les fichiers
from dotenv import load_dotenv # Pour charger les variables d'environnement (clés API)
import pandas as pd # Pour la manipulation des données

# Charger les variables d'environnement
load_dotenv("../.env")
openai_api_key = os.getenv("OPENAI_API_KEY")

In [ ]:
# Créer le modèle d'embedding OpenAI
embedding_function = OpenAIEmbeddings(
    api_key=openai_api_key,
    model="text-embedding-3-small"
)

# Charger les données comme dans le notebook 05 (approche simplifiée)
df_meta = pd.read_csv("../data/ready_for_embedding/chunks_with_metadata.csv")

In [8]:
# Créer les documents LangChain
from langchain.schema import Document
documents = [
    Document(
        page_content=row["text"],
        metadata={
            "chunk_id": row["chunk_id"],
            "source": row["source"],
            "page": row["page"],
            "theme": row["theme"] if "theme" in row else "général",
            "niveau": row["niveau"] if "niveau" in row else "moyen",
            "type": row["type"] if "type" in row else "informatif"
        }
    )
    for _, row in df_meta.iterrows()
]

In [9]:
# Initialiser le LLM
llm = ChatOpenAI(
    api_key=openai_api_key,
    model="gpt-4o",
    temperature=0.7
)

print("✅ Vectorstore et LLM initialisés avec succès !")

✅ Vectorstore et LLM initialisés avec succès !

In [10]:
# Fonction pour construire le prompt avec le contexte et la question

def build_prompt(context, question):
    return f"""
Tu es *Complice*, un assistant bienveillant qui aide les adolescents autistes à mieux comprendre les émotions, les relations sociales et les situations du quotidien.

Voici des extraits de documents pertinents :
{context}

Question : {question}

Réponds en français, avec clarté, douceur et concision. Utilise un ton rassurant, inclusif et jamais culpabilisant. Si la réponse est incertaine, propose des pistes ou invite à en discuter avec un adulte de confiance.
"""

In [11]:
# Fonction RAG avec affichage des chunks utilisés (API mise à jour)

def rag_verbose(question, k=5):
    docs = vectorstore.similarity_search(question, k=k)
    context = "\n\n".join([doc.page_content for doc in docs])
    prompt = build_prompt(context, question)
    
    # Utiliser la nouvelle méthode d'invocation
    response = llm.invoke([{"role": "user", "content": prompt}])

    return {
        "question": question,
        "response": response.content,
        "chunks": [doc.page_content for doc in docs],
        "sources": [doc.metadata.get("source", "inconnu") for doc in docs]
    }

In [12]:
# Test rapide avec quelques questions seulement (pour éviter la lenteur)

# Mode test rapide : seulement 3 questions pour commencer
questions_test = [
    "Pourquoi certaines personnes sont autistes ?",
    "Comment gérer mes émotions quand je suis en colère ?",
    "Comment faire des amis quand on est autiste ?"
]

print("🧪 Test rapide avec 3 questions...")
results_test = []

for q in questions_test:
    output = rag_verbose(q)
    print(f"\n🟦 Question : {output['question']}")
    print(f"🧠 Réponse : {output['response'][:200]}...")
    print(f"📚 Sources : {', '.join(set(output['sources']))}")
    
    # Note automatique (pour test rapide)
    output["rating"] = 2  # Note moyenne par défaut
    results_test.append(output)

print(f"\n✅ Test rapide terminé ! {len(results_test)} questions traitées.")

🧪 Test rapide avec 3 questions...

🟦 Question : Pourquoi certaines personnes sont autistes ?
🧠 Réponse : L'autisme est un sujet complexe et les scientifiques travaillent encore pour mieux comprendre ses causes. Ce que nous savons, c'est que l'autisme est souvent lié à des facteurs génétiques, ce qui sign...
📚 Sources : Penser-en-images_9782738143129, L'autisme explique par un autis - Thibaud Moulas, Comprendre_lautisme_pour_les_nuls

🟦 Question : Pourquoi certaines personnes sont autistes ?
🧠 Réponse : L'autisme est un sujet complexe et les scientifiques travaillent encore pour mieux comprendre ses causes. Ce que nous savons, c'est que l'autisme est souvent lié à des facteurs génétiques, ce qui sign...
📚 Sources : Penser-en-images_9782738143129, L'autisme explique par un autis - Thibaud Moulas, Comprendre_lautisme_pour_les_nuls

🟦 Question : Comment gérer mes émotions quand je suis en colère ?
🧠 Réponse : Quand tu ressens de la colère, il est important de te rappeler que c'est une émotion normale et que tu n'es pas seul à la ressentir. Voici quelques étapes qui pourraient t'aider à gérer ces moments :
...
📚 Sources : Penser-en-images_9782738143129, 683956044-Le-Syndrome-dAsperger-Guide-Complet, Comprendre_lautisme_pour_les_nuls

🟦 Question : Comment gérer mes émotions quand je suis en colère ?
🧠 Réponse : Quand tu ressens de la colère, il est important de te rappeler que c'est une émotion normale et que tu n'es pas seul à la ressentir. Voici quelques étapes qui pourraient t'aider à gérer ces moments :
...
📚 Sources : Penser-en-images_9782738143129, 683956044-Le-Syndrome-dAsperger-Guide-Complet, Comprendre_lautisme_pour_les_nuls

🟦 Question : Comment faire des amis quand on est autiste ?
🧠 Réponse : Faire des amis quand on est autiste peut sembler difficile, mais c'est tout à fait possible avec un peu de patience et de pratique. Voici quelques conseils qui pourraient t'aider :

1. **Observe et ap...
📚 Sources : Etre autiste et ado_ Strategies - Inconnu(e), Être autiste et réussir sa vie - Sherman Sezibera, Comprendre_lautisme_pour_les_nuls

✅ Test rapide terminé ! 3 questions traitées.

🟦 Question : Comment faire des amis quand on est autiste ?
🧠 Réponse : Faire des amis quand on est autiste peut sembler difficile, mais c'est tout à fait possible avec un peu de patience et de pratique. Voici quelques conseils qui pourraient t'aider :

1. **Observe et ap...
📚 Sources : Etre autiste et ado_ Strategies - Inconnu(e), Être autiste et réussir sa vie - Sherman Sezibera, Comprendre_lautisme_pour_les_nuls

✅ Test rapide terminé ! 3 questions traitées.

In [13]:
# Boucle de test complète avec annotation manuelle (OPTIONNELLE - peut être lente)

# ⚠️ ATTENTION : Cette cellule peut prendre 15-30 minutes à exécuter
# Exécutez d'abord le test rapide ci-dessus !

# Décommentez la ligne suivante pour activer la boucle complète
RUN_FULL_TEST = True  # Changez en True pour lancer le test complet

if RUN_FULL_TEST:
    questions = [
        "Pourquoi certaines personnes sont autistes ?",
        "Est-ce que l'autisme se guérit ?",
        "Comment savoir si je suis autiste ?",
        "Est-ce ma faute si je suis autiste ?",
        "Comment gérer mes émotions quand je suis en colère ?",
        "Comment faire des amis quand on est autiste ?",
        "Pourquoi j'ai du mal à comprendre les expressions faciales des autres ?",
        "Comment expliquer à mes amis que je suis autiste ?",
        "Que faire si je me sens submergé par les bruits ou les lumières ?",
        "Est-ce que je suis malade mentalement parce que je suis autiste ?",
        "Comment gérer l'anxiété et le stress au lycée ?",
        "Comment faire pour mieux dormir la nuit ?",
        "Pourquoi j'ai du mal à me faire des amis ?",
        "Comment faire pour surmonter ma peur des autres ?",
        "Est-ce que je suis bizarre parce que je suis autiste ?",
        "Comment faire pour mieux m'organiser au quotidien ?",
        "Pourquoi j'ai du mal à comprendre les blagues et l'humour des autres ?",
        "Comment faire pour surmonter le stress face aux contrôles au lycée ?",
    ]

    results = []

    print(f"🔄 Démarrage du test complet avec {len(questions)} questions...")
    
    for i, q in enumerate(questions, 1):
        print(f"\n{'='*60}")
        print(f"Question {i}/{len(questions)}")
        
        output = rag_verbose(q)
        print(f"\n🟦 Question : {output['question']}")
        print(f"🧠 Réponse : {output['response']}\n")
        for j, chunk in enumerate(output['chunks'], 1):
            print(f"🔹 Chunk {j} — Source : {output['sources'][j-1]}")
            print(chunk[:300] + "...\n")

        # Annotation manuelle
        rating = input("Pertinence de la réponse (0 = hors sujet, 1 = partielle, 2 = pertinente, 3 = excellente) : ")
        output["rating"] = int(rating)
        results.append(output)
        
    print(f"\n✅ Test complet terminé ! {len(results)} questions traitées.")
    
else:
    print("⏭️ Test complet désactivé. Changez RUN_FULL_TEST = True pour l'activer.")
    results = results_test  # Utiliser les résultats du test rapide

🔄 Démarrage du test complet avec 18 questions...

============================================================
Question 1/18

🟦 Question : Pourquoi certaines personnes sont autistes ?
🧠 Réponse : L'autisme est un sujet complexe et les scientifiques ne connaissent pas encore toutes les raisons pour lesquelles certaines personnes sont autistes. Il semble que l'autisme soit le résultat d'une combinaison de facteurs génétiques et environnementaux. Cela signifie que des éléments présents dans les gènes, ainsi que certaines conditions pendant la grossesse, pourraient jouer un rôle.

Par exemple, certaines recherches ont exploré le lien entre les troubles auto-immuns et l'autisme, mais rien n'est encore prouvé de manière définitive. De plus, l'autisme est très varié et se manifeste différemment chez chaque personne, ce qui rend sa compréhension encore plus complexe.

Il est important de se rappeler que l'autisme fait partie de la diversité humaine et que chaque personne autiste a ses propres talents et défis. Si tu as des questions ou si tu te sens concerné, n'hésite pas à en parler avec un adulte de confiance qui pourra t'aider à mieux comprendre et à trouver les ressources dont tu as besoin.

🔹 Chunk 1 — Source : Comprendre_lautisme_pour_les_nuls
enfants de mères exposées au virus de la rubéole ou de la rougeole au début de leur grossesse. Dans la famille de nombreuses personnes autistes, on remarque des personnes atteintes de maladies auto-immunes telles que le diabète ou l’arthrite rhumatoïde, suggérant un lien entre l’autisme et les probl...

🔹 Chunk 2 — Source : L'autisme explique par un autis - Thibaud Moulas
Certains enfants autistes ont développé des handicaps en renonçant à exprimer leur véritable potentiel et en se limitant à répondre à une demande qui les sousestime3. Pour d’autres, ces idées reçues ont servi les intérêts de cruels traitements comme l’enfermement psychiatrique, le placement abusif d...

🔹 Chunk 3 — Source : Penser-en-images_9782738143129
faibles compétences sociales. Les parents, sans être autistes eux-mêmes, présentaient quelques caractéristiques qui rap- pelaient ceux de leurs enfants autistes. Dans une étude effec- tuée par Rebecca Landa et d’autres chercheurs de l’école de médecine Johns Hopkins, on a demandé aux parents d’ima- ...

🔹 Chunk 4 — Source : Comprendre_lautisme_pour_les_nuls
catégories d’autisme. La personne peut ne pas être pleinement verbale ou avoir des mouvements stéréotypés (battre des mains, se balancer), mais il ou elle n’a pas assez de symptômes pour être considérée comme autiste. Cet entre-deux peut être la cause d’une plus grande difficulté à obtenir les compe...

🔹 Chunk 5 — Source : L'autisme explique par un autis - Thibaud Moulas
Chapitre 2 Les autistes dans l’Histoire Et si les personnes autistes, par leur inadaptation et leur résistance aux normes sociales, étaient les personnes les plus saines qui soient ? Julie Dachez En théorie, l’autisme existe depuis la Préhistoire. Depuis ce temps, les autistes sont restés invisibles...


🟦 Question : Pourquoi certaines personnes sont autistes ?
🧠 Réponse : L'autisme est un sujet complexe et les scientifiques ne connaissent pas encore toutes les raisons pour lesquelles certaines personnes sont autistes. Il semble que l'autisme soit le résultat d'une combinaison de facteurs génétiques et environnementaux. Cela signifie que des éléments présents dans les gènes, ainsi que certaines conditions pendant la grossesse, pourraient jouer un rôle.

Par exemple, certaines recherches ont exploré le lien entre les troubles auto-immuns et l'autisme, mais rien n'est encore prouvé de manière définitive. De plus, l'autisme est très varié et se manifeste différemment chez chaque personne, ce qui rend sa compréhension encore plus complexe.

Il est important de se rappeler que l'autisme fait partie de la diversité humaine et que chaque personne autiste a ses propres talents et défis. Si tu as des questions ou si tu te sens concerné, n'hésite pas à en parler avec un adulte de confiance qui pourra t'aider à mieux comprendre et à trouver les ressources dont tu as besoin.

🔹 Chunk 1 — Source : Comprendre_lautisme_pour_les_nuls
enfants de mères exposées au virus de la rubéole ou de la rougeole au début de leur grossesse. Dans la famille de nombreuses personnes autistes, on remarque des personnes atteintes de maladies auto-immunes telles que le diabète ou l’arthrite rhumatoïde, suggérant un lien entre l’autisme et les probl...

🔹 Chunk 2 — Source : L'autisme explique par un autis - Thibaud Moulas
Certains enfants autistes ont développé des handicaps en renonçant à exprimer leur véritable potentiel et en se limitant à répondre à une demande qui les sousestime3. Pour d’autres, ces idées reçues ont servi les intérêts de cruels traitements comme l’enfermement psychiatrique, le placement abusif d...

🔹 Chunk 3 — Source : Penser-en-images_9782738143129
faibles compétences sociales. Les parents, sans être autistes eux-mêmes, présentaient quelques caractéristiques qui rap- pelaient ceux de leurs enfants autistes. Dans une étude effec- tuée par Rebecca Landa et d’autres chercheurs de l’école de médecine Johns Hopkins, on a demandé aux parents d’ima- ...

🔹 Chunk 4 — Source : Comprendre_lautisme_pour_les_nuls
catégories d’autisme. La personne peut ne pas être pleinement verbale ou avoir des mouvements stéréotypés (battre des mains, se balancer), mais il ou elle n’a pas assez de symptômes pour être considérée comme autiste. Cet entre-deux peut être la cause d’une plus grande difficulté à obtenir les compe...

🔹 Chunk 5 — Source : L'autisme explique par un autis - Thibaud Moulas
Chapitre 2 Les autistes dans l’Histoire Et si les personnes autistes, par leur inadaptation et leur résistance aux normes sociales, étaient les personnes les plus saines qui soient ? Julie Dachez En théorie, l’autisme existe depuis la Préhistoire. Depuis ce temps, les autistes sont restés invisibles...


============================================================
Question 2/18

============================================================
Question 2/18

🟦 Question : Est-ce que l'autisme se guérit ?
🧠 Réponse : L'autisme n'est pas une maladie qui se guérit avec des médicaments ou des traitements. C'est une particularité du fonctionnement du cerveau, une façon différente d'interagir avec le monde. Certaines personnes autistes ne souhaitent pas être "guéries" car elles considèrent l'autisme comme une partie de leur identité qui apporte aussi des talents et une diversité précieuse à la société.

Il est important de comprendre que chaque personne autiste est unique, avec ses propres forces et défis. Plutôt que de chercher à guérir, il peut être plus utile d'apprendre à mieux se comprendre et à développer des stratégies pour naviguer dans le monde.

Si tu as des questions ou des inquiétudes, n'hésite pas à en parler avec un adulte de confiance, comme un parent, un enseignant ou un thérapeute, qui pourra t'écouter et t'aider à trouver les réponses dont tu as besoin.

🔹 Chunk 1 — Source : L'autisme explique par un autis - Thibaud Moulas
L’autisme était perçu comme une maladie qui pouvait se guérir grâce à des médicaments, des thérapies ou des traitements psychanalytiques entre autres. Dès 1980, la recherche scientifique internationale a commencé à corriger la définition de l’autisme. Cependant, la France est restée coincée dans...

🔹 Chunk 2 — Source : Comprendre_lautisme_pour_les_nuls
Un certain nombre de personnes autistes soutiennent ainsi qu’elles n’ont pas besoin ou ne veulent pas être guéries, et soulignent que le rejet des gens qui sont différents de la norme est le plus grand problème. Beaucoup affirment que l’autisme, en particulier ce qui dans les classifications antérie...

🔹 Chunk 3 — Source : Penser-en-images_9782738143129
Il peut exister une forme légère ou sévère de l’autisme en chacun des points du spectre. La sévérité comme le rapport entre les deux composantes peuvent varier, et chaque cas d’autisme est différent. Quand un autiste progresse à la suite d’une intervention éducative ou médicale, il arrive que la sév...

🔹 Chunk 4 — Source : L'autisme explique par un autis - Thibaud Moulas
pas entendu ? Les autistes n’auraient-ils pas le droit d’avoir un mouvement pour se faire respecter ? De nombreuses personnes ont encore une vision erronée de l’autisme. Et en refusant de la remettre en cause, ils propagent de mauvaises informations. Vaincre l’autisme ne fait pas exception. Mais l’a...

🔹 Chunk 5 — Source : Comprendre_lautisme_pour_les_nuls
Il est probable que les chercheurs trouvent un jour « la » cause de l’autisme, et beaucoup de gens pensent qu’ils l’ont déjà trouvée ; toutefois, cette cause ne s’appliquera sans doute pas à toutes les formes d’autisme. Il faut donc garder à l’esprit ceci : l’autisme n’est pas de votre faute. Votre ...


🟦 Question : Est-ce que l'autisme se guérit ?
🧠 Réponse : L'autisme n'est pas une maladie qui se guérit avec des médicaments ou des traitements. C'est une particularité du fonctionnement du cerveau, une façon différente d'interagir avec le monde. Certaines personnes autistes ne souhaitent pas être "guéries" car elles considèrent l'autisme comme une partie de leur identité qui apporte aussi des talents et une diversité précieuse à la société.

Il est important de comprendre que chaque personne autiste est unique, avec ses propres forces et défis. Plutôt que de chercher à guérir, il peut être plus utile d'apprendre à mieux se comprendre et à développer des stratégies pour naviguer dans le monde.

Si tu as des questions ou des inquiétudes, n'hésite pas à en parler avec un adulte de confiance, comme un parent, un enseignant ou un thérapeute, qui pourra t'écouter et t'aider à trouver les réponses dont tu as besoin.

🔹 Chunk 1 — Source : L'autisme explique par un autis - Thibaud Moulas
L’autisme était perçu comme une maladie qui pouvait se guérir grâce à des médicaments, des thérapies ou des traitements psychanalytiques entre autres. Dès 1980, la recherche scientifique internationale a commencé à corriger la définition de l’autisme. Cependant, la France est restée coincée dans...

🔹 Chunk 2 — Source : Comprendre_lautisme_pour_les_nuls
Un certain nombre de personnes autistes soutiennent ainsi qu’elles n’ont pas besoin ou ne veulent pas être guéries, et soulignent que le rejet des gens qui sont différents de la norme est le plus grand problème. Beaucoup affirment que l’autisme, en particulier ce qui dans les classifications antérie...

🔹 Chunk 3 — Source : Penser-en-images_9782738143129
Il peut exister une forme légère ou sévère de l’autisme en chacun des points du spectre. La sévérité comme le rapport entre les deux composantes peuvent varier, et chaque cas d’autisme est différent. Quand un autiste progresse à la suite d’une intervention éducative ou médicale, il arrive que la sév...

🔹 Chunk 4 — Source : L'autisme explique par un autis - Thibaud Moulas
pas entendu ? Les autistes n’auraient-ils pas le droit d’avoir un mouvement pour se faire respecter ? De nombreuses personnes ont encore une vision erronée de l’autisme. Et en refusant de la remettre en cause, ils propagent de mauvaises informations. Vaincre l’autisme ne fait pas exception. Mais l’a...

🔹 Chunk 5 — Source : Comprendre_lautisme_pour_les_nuls
Il est probable que les chercheurs trouvent un jour « la » cause de l’autisme, et beaucoup de gens pensent qu’ils l’ont déjà trouvée ; toutefois, cette cause ne s’appliquera sans doute pas à toutes les formes d’autisme. Il faut donc garder à l’esprit ceci : l’autisme n’est pas de votre faute. Votre ...


============================================================
Question 3/18

============================================================
Question 3/18

🟦 Question : Comment savoir si je suis autiste ?
🧠 Réponse : Se poser la question de savoir si on est autiste est tout à fait normal et c'est un premier pas vers une meilleure compréhension de soi-même. Les personnes autistes peuvent avoir des façons différentes de communiquer et d'interagir avec les autres, ainsi que des sensibilités particulières.

Voici quelques pistes pour explorer cette question :

1. **Renseigne-toi** : Tu peux commencer par lire sur l'autisme, consulter des sites internet fiables ou lire des livres sur le sujet. Comprendre les caractéristiques de l'autisme peut t'aider à voir si tu t'y reconnais.

2. **Tests d'autoévaluation** : Il existe des outils comme le test ASQ (Autism Spectrum Quotient) qui peuvent donner des indications sur la possibilité d'un autisme. C'est un point de départ, mais cela ne remplace pas un diagnostic professionnel.

3. **Parle-en** : Discuter de tes réflexions avec un adulte de confiance, comme un parent, un enseignant ou un conseiller, peut être très utile. Ils peuvent t'accompagner dans cette démarche et éventuellement t'aider à consulter un professionnel.

4. **Consulte un professionnel** : Pour obtenir un diagnostic clair, il est important de consulter un professionnel qualifié, comme un psychologue ou un psychiatre. Ils pourront t'évaluer et te donner des conseils adaptés.

Rappelle-toi, être autiste n'est ni une bonne ni une mauvaise chose, c'est une façon d'être qui a ses propres forces et défis. Prends ton temps et sois bienveillant avec toi-même dans ce processus.

🔹 Chunk 1 — Source : Comprendre_lautisme_pour_les_nuls
Si vous pensez être autiste, ou si vous connaissez une personne dans ce cas, vous avez un certain nombre de possibilités (en plus de la lecture du présent ouvrage, bien sûr) : » Vous pouvez consulter des sites Web, tels que ceux listés dans les annexes pour avoir de l’aide ; » Vous pouvez vous famil...

🔹 Chunk 2 — Source : Penser-en-images_9782738143129
Si j’avais deux ans aujourd’hui, on diagnostiquerait chez moi un autisme du type Kanner, car le développement du langage a été anormal et retardé. En revanche, si on examinait l’adulte que je suis en réalité, on dirait proba- blement que je suis atteinte du syndrome d’Asperger parce que je réussis u...

🔹 Chunk 3 — Source : L'autisme explique par un autis - Thibaud Moulas
Préambule Je me heurte parfois à une telle incompréhension de la part de mes contemporains qu’un épouvantable doute m’étreint : Suis-je bien de cette planète ? Et si oui, cela ne prouve-t-il pas qu’eux sont d’ailleurs ? Pierre Desproges Je me suis toujours senti différent des autres. Cependant, je n...

🔹 Chunk 4 — Source : Comprendre_lautisme_pour_les_nuls
Faut-il dire que l’on est autiste ou pas ? La décision de révéler son autisme est importante. Nous pensons que vous ne devriez le révéler qu’à ceux qui ont besoin de le savoir. Et quand est-on dans ce cas ? Lorsque les effets de l’autisme ont un impact significatif sur une relation et que vous avez ...

🔹 Chunk 5 — Source : Etre autiste et ado_ Strategies - Inconnu(e)
1 L’AUTISME, QU’EST-CE QUE C’EST ? Comme c’est mon premier billet officiel (un texte de blogue s’appelle un billet), je me suis dit qu’il serait probablement logique que je t’explique ce qu’il faut faire pour être autiste. Hum… Ou plutôt ce qui décrit une personne autiste, au cas où tout cela ne ser...


🟦 Question : Comment savoir si je suis autiste ?
🧠 Réponse : Se poser la question de savoir si on est autiste est tout à fait normal et c'est un premier pas vers une meilleure compréhension de soi-même. Les personnes autistes peuvent avoir des façons différentes de communiquer et d'interagir avec les autres, ainsi que des sensibilités particulières.

Voici quelques pistes pour explorer cette question :

1. **Renseigne-toi** : Tu peux commencer par lire sur l'autisme, consulter des sites internet fiables ou lire des livres sur le sujet. Comprendre les caractéristiques de l'autisme peut t'aider à voir si tu t'y reconnais.

2. **Tests d'autoévaluation** : Il existe des outils comme le test ASQ (Autism Spectrum Quotient) qui peuvent donner des indications sur la possibilité d'un autisme. C'est un point de départ, mais cela ne remplace pas un diagnostic professionnel.

3. **Parle-en** : Discuter de tes réflexions avec un adulte de confiance, comme un parent, un enseignant ou un conseiller, peut être très utile. Ils peuvent t'accompagner dans cette démarche et éventuellement t'aider à consulter un professionnel.

4. **Consulte un professionnel** : Pour obtenir un diagnostic clair, il est important de consulter un professionnel qualifié, comme un psychologue ou un psychiatre. Ils pourront t'évaluer et te donner des conseils adaptés.

Rappelle-toi, être autiste n'est ni une bonne ni une mauvaise chose, c'est une façon d'être qui a ses propres forces et défis. Prends ton temps et sois bienveillant avec toi-même dans ce processus.

🔹 Chunk 1 — Source : Comprendre_lautisme_pour_les_nuls
Si vous pensez être autiste, ou si vous connaissez une personne dans ce cas, vous avez un certain nombre de possibilités (en plus de la lecture du présent ouvrage, bien sûr) : » Vous pouvez consulter des sites Web, tels que ceux listés dans les annexes pour avoir de l’aide ; » Vous pouvez vous famil...

🔹 Chunk 2 — Source : Penser-en-images_9782738143129
Si j’avais deux ans aujourd’hui, on diagnostiquerait chez moi un autisme du type Kanner, car le développement du langage a été anormal et retardé. En revanche, si on examinait l’adulte que je suis en réalité, on dirait proba- blement que je suis atteinte du syndrome d’Asperger parce que je réussis u...

🔹 Chunk 3 — Source : L'autisme explique par un autis - Thibaud Moulas
Préambule Je me heurte parfois à une telle incompréhension de la part de mes contemporains qu’un épouvantable doute m’étreint : Suis-je bien de cette planète ? Et si oui, cela ne prouve-t-il pas qu’eux sont d’ailleurs ? Pierre Desproges Je me suis toujours senti différent des autres. Cependant, je n...

🔹 Chunk 4 — Source : Comprendre_lautisme_pour_les_nuls
Faut-il dire que l’on est autiste ou pas ? La décision de révéler son autisme est importante. Nous pensons que vous ne devriez le révéler qu’à ceux qui ont besoin de le savoir. Et quand est-on dans ce cas ? Lorsque les effets de l’autisme ont un impact significatif sur une relation et que vous avez ...

🔹 Chunk 5 — Source : Etre autiste et ado_ Strategies - Inconnu(e)
1 L’AUTISME, QU’EST-CE QUE C’EST ? Comme c’est mon premier billet officiel (un texte de blogue s’appelle un billet), je me suis dit qu’il serait probablement logique que je t’explique ce qu’il faut faire pour être autiste. Hum… Ou plutôt ce qui décrit une personne autiste, au cas où tout cela ne ser...


============================================================
Question 4/18

============================================================
Question 4/18

🟦 Question : Est-ce ma faute si je suis autiste ?
🧠 Réponse : Non, ce n'est absolument pas ta faute si tu es autiste. L'autisme est une différence neurologique, une manière différente dont le cerveau est câblé. Ce n'est pas quelque chose que l'on choisit ou dont on est responsable. C'est simplement une partie de ce qui te rend unique.

Il est important de se rappeler que tout le monde a des forces et des défis, et que l'autisme peut apporter des talents particuliers ainsi que des difficultés. Si tu te sens concerné par certaines questions ou émotions, parler avec un adulte de confiance, comme un parent, un enseignant ou un professionnel de la santé, peut être très bénéfique.

N'hésite pas à explorer et comprendre cette partie de toi avec bienveillance, et souviens-toi que tu n'es pas seul. Il y a des gens qui te soutiennent et qui sont là pour t'aider à naviguer dans tes expériences.

🔹 Chunk 1 — Source : Être autiste et réussir sa vie - Sherman Sezibera
L’autisme n’est pas une maladie. Toutefois, selon certains signes ou symptômes, on définira de quel spectre autistique il s’agit. En ce qui me concerne, j’ai le syndrome d’Asperger. Cette condition n’a rien d’imparfait en soi. Nous sommes venus au monde ensemble. C’est un peu comme naître grand, pet...

🔹 Chunk 2 — Source : Penser-en-images_9782738143129

In [14]:
# Sauvegarde des résultats
df = pd.DataFrame(results)
df.to_csv("../data/validation_results.csv", index=False)

In [15]:
df.head(20)

,question,response,chunks,sources,rating
0,Pourquoi certaines personnes sont autistes ?,L'autisme est un sujet complexe et les scienti...,[enfants de mères exposées au virus de la rubé...,"[Comprendre_lautisme_pour_les_nuls, L'autisme ...",3
1,Est-ce que l'autisme se guérit ?,L'autisme n'est pas une maladie qui se guérit ...,[L’autisme était perçu comme une maladie qui p...,[L'autisme explique par un autis - Thibaud Mou...,2
2,Comment savoir si je suis autiste ?,Se poser la question de savoir si on est autis...,"[Si vous pensez être autiste, ou si vous conna...","[Comprendre_lautisme_pour_les_nuls, Penser-en-...",3
3,Est-ce ma faute si je suis autiste ?,"Non, ce n'est absolument pas ta faute si tu es...","[L’autisme n’est pas une maladie. Toutefois, s...",[Être autiste et réussir sa vie - Sherman Sezi...,2
4,Comment gérer mes émotions quand je suis en co...,"Gérer la colère peut être un défi, mais c'est ...",[suivante vous donne d’autres astuces pour sur...,"[Comprendre_lautisme_pour_les_nuls, Comprendre...",3
5,Comment faire des amis quand on est autiste ?,Faire des amis quand on est autiste peut sembl...,"[autisme, développer des relations amicales pe...","[Comprendre_lautisme_pour_les_nuls, Comprendre...",3
6,Pourquoi j'ai du mal à comprendre les expressi...,Comprendre les expressions faciales des autres...,[avoir un à portée de main.) • Demande à l’aut...,"[Etre autiste et ado_ Strategies - Inconnu(e),...",2
7,Comment expliquer à mes amis que je suis autis...,Expliquer à tes amis que tu es autiste peut êt...,[effet miroir lui fait penser que nous partage...,[Être autiste et réussir sa vie - Sherman Sezi...,3
8,Que faire si je me sens submergé par les bruit...,Si tu te sens submergé par les bruits ou les l...,[341 Sensibilité sensorielle Cela peut mener à...,[683956044-Le-Syndrome-dAsperger-Guide-Complet...,3
9,Est-ce que je suis malade mentalement parce qu...,"Non, tu n'es pas malade mentalement parce que ...","[L’autisme n’est pas une maladie. Toutefois, s...",[Être autiste et réussir sa vie - Sherman Sezi...,2
10,Comment gérer l'anxiété et le stress au lycée ?,Gérer l'anxiété et le stress au lycée peut êtr...,[IDÉE 86 FACE À L’ANXIÉTÉ ET AU STRESS Certain...,[100 idees pour enseigner les ha - Mehdi Lirat...,3
11,Comment faire pour mieux dormir la nuit ?,"Pour mieux dormir la nuit, voici quelques cons...","[• Même si je n’étais pas d’accord au début, j...","[Etre autiste et ado_ Strategies - Inconnu(e),...",3
12,Pourquoi j'ai du mal à me faire des amis ?,Il peut être difficile de se faire des amis po...,"[Lorsqu’il s’agit des amitiés, j’ai deux diffi...","[Etre autiste et ado_ Strategies - Inconnu(e),...",3
13,Comment faire pour surmonter ma peur des autres ?,Surmonter la peur des autres peut être un défi...,[Je pense que je succomberais plus vite encore...,"[Bienvenue dans mon monde - Paul El Kharrat, Ê...",2
14,Est-ce que je suis bizarre parce que je suis a...,"Non, tu n'es pas bizarre parce que tu es autis...","[L’autisme n’est pas une maladie. Toutefois, s...",[Être autiste et réussir sa vie - Sherman Sezi...,3
15,Comment faire pour mieux m'organiser au quotid...,"Pour mieux t'organiser au quotidien, voici que...",[Pourquoi pas un système de récompense pour to...,[100 idees pour enseigner les ha - Mehdi Lirat...,2
16,Pourquoi j'ai du mal à comprendre les blagues ...,C'est tout à fait normal de parfois avoir du m...,[C’est peut-être aussi un moyen de m’entraîner...,"[Bienvenue dans mon monde - Paul El Kharrat, E...",3
17,Comment faire pour surmonter le stress face au...,Surmonter le stress face aux contrôles au lycé...,[IDÉE 86 FACE À L’ANXIÉTÉ ET AU STRESS Certain...,[100 idees pour enseigner les ha - Mehdi Lirat...,2

# Utilisation de RAGAS (outil conçu pour évaluer les systèmes RAG avec des métriques précises)

L’intégration de RAGAS dans ce notebook de validation est une manière de calibrer finement les réponses de Complice, surtout dans un contexte aussi délicat et humain: l'outil final de ce projet s'adresse à de jeunes personnes vulnérables donc il est important de calibrer les réponses de manière à ce qu'elles soient pertinentes et bienveillantes.

Préparer les données au format RAGAS, c'est à dire un dataset structuré avec les champs suivants :

    - question — la requête utilisateur

    - ground_truth — la réponse attendue (si disponible)

    - contexts — les chunks récupérés

    - answer — la réponse générée par le LLM

    - metadata — optionnel, infos sur les sources
    
Nous allons construire ce dataset à partir de la boucle de validation effectué ci-avant.

In [7]:
# Changement du nom de la colonne "response" en "answer" pour compatibilité avec RAGAS
df = df.rename(columns={"response": "answer"})

In [8]:
# Verification des colonnes dans le dataframe
df.columns

Index(['question', 'answer', 'chunks', 'sources', 'rating'], dtype='object')

In [ ]:
from ragas import evaluate # Pour l'évaluation RAGAS
from ragas.metrics import context_precision, faithfulness, answer_relevancy # Pour les métriques d'évaluation
from datasets import Dataset  # Hugging Face pour la gestion des datasets

# Préparation des données pour RAGAS

data = {
    "question": [],
    "answer": [],
    "contexts": [],
    "ground_truth": []  # Tu peux remplir avec des réponses de référence ou laisser vide
}

for item in df.to_dict(orient="records"):
    data["question"].append(item["question"])
    data["answer"].append(item["answer"])
    data["contexts"].append(item["chunks"])  # ✅ ici on utilise "chunks"
    data["ground_truth"].append("")  # ou une réponse de référence si tu en as

ragas_dataset = Dataset.from_dict(data)

In [ ]:
# Évaluation avec RAGAS en utilisant le df construit grâce à la boucle de test

from ragas import evaluate # Pour l'évaluation RAGAS
from ragas.metrics import context_precision, faithfulness, answer_relevancy # Pour les métriques d'évaluation

result = evaluate(
    ragas_dataset,
    metrics=[context_precision, faithfulness, answer_relevancy]
)

result.to_pandas()

Evaluating:   0%|          | 0/54 [00:00<?, ?it/s]Exception raised in Job[8]: IndexError(list index out of range)
Evaluating:   2%|▏         | 1/54 [00:01<01:33,  1.77s/it]Exception raised in Job[14]: IndexError(list index out of range)
Exception raised in Job[11]: IndexError(list index out of range)
Exception raised in Job[2]: IndexError(list index out of range)
Evaluating:   4%|▎         | 2/54 [00:03<01:36,  1.86s/it]Exception raised in Job[5]: IndexError(list index out of range)
Evaluating:   9%|▉         | 5/54 [00:10<01:48,  2.22s/it]Exception raised in Job[17]: IndexError(list index out of range)
Evaluating:  11%|█         | 6/54 [00:17<02:45,  3.46s/it]Exception raised in Job[20]: IndexError(list index out of range)
Evaluating:  39%|███▉      | 21/54 [01:29<01:49,  3.33s/it]Exception raised in Job[32]: IndexError(list index out of range)
Evaluating:  57%|█████▋    | 31/54 [02:17<02:08,  5.60s/it]Exception raised in Job[44]: IndexError(list index out of range)
Evaluating:  72%|███████▏  | 39/54 [02:41<00:45,  3.02s/it]Exception raised in Job[50]: IndexError(list index out of range)
Evaluating:  98%|█████████▊| 53/54 [04:14<00:13, 13.04s/it]Exception raised in Job[31]: TimeoutError()
Evaluating: 100%|██████████| 54/54 [04:14<00:00,  4.71s/it]

,user_input,retrieved_contexts,response,reference,context_precision,faithfulness,answer_relevancy
0,Pourquoi certaines personnes sont autistes ?,[enfants de mères exposées au virus de la rubé...,Salut ! La question de savoir pourquoi certain...,,0.000000,0.800000,NaN
1,Est-ce que l'autisme se guérit ?,[Utiliser les méthodes naturelles et biomédica...,L'autisme n'est pas quelque chose que l'on peu...,,0.250000,0.636364,NaN
2,Comment savoir si je suis autiste ?,[Comment vous dire ce que je suis ? Ce que je ...,Déterminer si tu es autiste peut être un proce...,,0.000000,1.000000,NaN
3,Est-ce ma faute si je suis autiste ?,"[Consciemment ou pas, à ce moment-là, je me su...","Non, ce n'est pas ta faute si tu es autiste. L...",,0.000000,0.538462,NaN
4,Comment gérer mes émotions quand je suis en co...,[suivante vous donne d’autres astuces pour sur...,"Gérer ses émotions, surtout la colère, peut êt...",,0.000000,1.000000,NaN
5,Comment faire des amis quand on est autiste ?,[TOP 10 DES STRATÉGIES D’AMITIÉ Choisis le typ...,Faire des amis quand on est autiste peut sembl...,,0.833333,1.000000,NaN
6,Pourquoi j'ai du mal à comprendre les expressi...,"[De même, j’ai remarqué que certains enfants a...",Comprendre les expressions faciales des autres...,,0.638889,0.714286,NaN
7,Comment expliquer à mes amis que je suis autis...,[Vous n’avez pas à inventer des explications p...,Expliquer à tes amis que tu es autiste peut se...,,0.200000,0.800000,0.000000
8,Que faire si je me sens submergé par les bruit...,[agacée par le bruit que fait une personne en ...,Si tu te sens submergé par les bruits ou les l...,,0.333333,0.347826,0.998265
9,Est-ce que je suis malade mentalement parce qu...,"[L’autisme n’est pas une maladie. Toutefois, s...","Non, tu n'es pas malade mentalement parce que ...",,1.000000,0.916667,0.929917
10,Comment gérer l'anxiété et le stress au lycée ?,[IDÉE 86 FACE À L’ANXIÉTÉ ET AU STRESS Certain...,Gérer l'anxiété et le stress au lycée peut êtr...,,0.500000,NaN,NaN
11,Comment faire pour mieux dormir la nuit ?,[Voici quelques stratégies qui fonctionnent bi...,"Pour mieux dormir la nuit, il y a plusieurs st...",,0.588889,1.000000,0.000000
12,Pourquoi j'ai du mal à me faire des amis ?,"[Lorsqu’il s’agit des amitiés, j’ai deux diffi...",Il peut être difficile de se faire des amis po...,,1.000000,1.000000,0.000000
13,Comment faire pour surmonter ma peur des autres ?,[agacée par le bruit que fait une personne en ...,Surmonter la peur des autres peut être un défi...,,0.333333,0.888889,0.000000
14,Est-ce que je suis bizarre parce que je suis a...,[où mes traits autistiques ne m’empêchent pas ...,Ce n'est pas parce que tu es autiste que tu es...,,0.000000,0.692308,NaN
15,Comment faire pour mieux m'organiser au quotid...,[Le réveil cassé 4 Téléphone : Informe ton éco...,"Pour mieux t'organiser au quotidien, voici que...",,1.000000,0.933333,0.000000
16,Pourquoi j'ai du mal à comprendre les blagues ...,[C’est peut-être aussi un moyen de m’entraîner...,C'est tout à fait normal de trouver parfois le...,,1.000000,0.642857,NaN
17,Comment faire pour surmonter le stress face au...,[De mauvais résultats 35 Assume tes responsabi...,Surmonter le stress face aux contrôles au lycé...,,0.000000,1.000000,0.979937

Interpretation: 

Ce tableau présente des scores entre 0 et 1 pour chaque métrique:

    - context_precision : les chunks sont-ils vraiment utiles ?

    - faithfulness : la réponse respecte-t-elle le contenu des chunks ?

    - answer_relevancy : la réponse est-elle bien alignée avec la question ?

Il nous permet de détecter les cas où le modèle hallucine, dévie du ton bienveillant, ou utilise des sources peu pertinentes.

Analyse des résultats obtenus:

📊 1. context_precision

Définition : Quelle proportion des chunks récupérés sont réellement utiles pour répondre à la question.

0.00 → 0.25 : Les chunks sont probablement hors sujet ou peu pertinents.

1.00 : Tous les chunks sont directement utiles à la réponse.

🔍 Ce qu'on observe :
Certaines questions ont une précision faible → chunks peu pertinents.

D'autres ont une précision parfaite → excellente récupération.

💡 Interprétation : Notre index FAISS fonctionne bien pour certaines questions, mais d’autres semblent mal matcher. 

On pourrait :

    - augmenter la granularité du chunking,

    - enrichir les métadonnées pour filtrer par thème,

    - tester une autre méthode d’embedding.

🧠 2. faithfulness

Définition : Est-ce que la réponse générée respecte le contenu des chunks ? (pas d’hallucination)

1.00 : La réponse est parfaitement fidèle aux sources.

< 0.70 : Risque de déviation ou d’invention.

🔍 Ce qu'on observe :

Les réponses sont globalement fidèles (souvent > 0.75).

Même quand les chunks sont peu pertinents, le LLM reste prudent.

💡 Interprétation : Notre prompt bienveillant et structuré joue un rôle clé ici. Nous pouvons être confiant sur la sécurité des réponses, même si les sources sont faibles.

🎯 3. answer_relevancy
Définition : Est-ce que la réponse répond bien à la question posée ?

1.00 : Réponse parfaitement pertinente.

0.00 : Réponse hors sujet ou vague.

🔍 Ce qu'on observe :

Cette métrique est NaN pour les lignes sans reference (ground truth).

    - Score élevé → réponse jugée pertinente.

    - Score nul → réponse jugée hors sujet (selon la référence).

💡 Interprétation : Pour que cette métrique soit calculée, nous devons fournir une reference (réponse de référence) dans ton dataset. Même quelques lignes bien calibrées suffisent pour enrichir l’analyse.

🧭 Pour la suite, nous allons ajouter des références  (ground truth) afin de mieux évaluer la métrique 'answer relevancy'. Pour ce faire, nous allons ajouter la colonne 'référence' qui sert à indiquer ce que serait une réponse idéale à la question posée.

In [11]:
# Réponses de référence pour comparaison

references = [
    "L’autisme est une condition neurodéveloppementale liée à des différences dans le fonctionnement du cerveau. Ce n’est ni une faute, ni une maladie.",
    "L’autisme ne se guérit pas, car ce n’est pas une maladie. On peut cependant apprendre à mieux vivre avec, grâce à des soutiens adaptés.",
    "Pour savoir si tu es autiste, il est important de consulter des professionnels spécialisés. Ils prendront en compte ton vécu et ton fonctionnement.",
    "Non, ce n’est absolument pas ta faute. L’autisme fait partie de qui tu es, et tu mérites d’être compris et respecté.",
    "Quand tu es en colère, tu peux essayer de respirer lentement, t’isoler un moment ou parler à un adulte de confiance. Il existe des stratégies pour t’aider.",
    "Faire des amis peut être difficile, mais possible. Cherche des personnes bienveillantes, sois toi-même et prends ton temps.",
    "Les expressions faciales peuvent être complexes à décoder. Tu peux apprendre à les reconnaître avec des outils ou des exemples concrets.",
    "Tu peux expliquer à tes amis que l’autisme influence ta manière de penser et de ressentir. S’ils sont ouverts, ils comprendront mieux qui tu es.",
    "Si tu te sens submergé, tu peux utiliser des bouchons d’oreilles, des lunettes filtrantes ou t’éloigner un moment. C’est normal de chercher des solutions.",
    "Non, tu n’es pas fou. Ressentir des choses différemment ne veut pas dire que quelque chose ne va pas. Tu as le droit d’être toi.",
    "Pour gérer le stress au lycée, tu peux organiser ton temps, parler à un adulte ou utiliser des techniques de relaxation. Tu n’es pas seul.",
    "Pour mieux dormir, essaie de garder une routine, d’éviter les écrans avant le coucher et de créer un environnement calme.",
    "Tu n’es pas seul à avoir du mal à te faire des amis. Cela peut prendre du temps, mais il existe des moyens pour créer des liens.",
    "La peur des autres peut venir de l’anxiété ou d’expériences passées. Tu peux apprendre à la surmonter avec des petits pas et du soutien.",
    "Tu n’es pas bizarre. Tu es unique, comme tout le monde. L’autisme ne te rend pas moins digne d’amitié ou de respect.",
    "Pour mieux t’organiser, tu peux utiliser des listes, des rappels visuels ou des routines. Trouve ce qui fonctionne pour toi.",
    "L’humour peut être subtil ou culturel. Tu peux apprendre à le décoder avec des exemples ou en demandant des explications.",
    "Pour gérer le stress des contrôles, prépare-toi à l’avance, repose-toi bien et parle de tes inquiétudes à un adulte. Tu as le droit d’être soutenu."
]

In [12]:
# Ajout des réponses de référence dans le dataframe
df["ground_truth"] = references
df.head(20)

,question,answer,chunks,sources,rating,ground_truth
0,Pourquoi certaines personnes sont autistes ?,Salut ! La question de savoir pourquoi certain...,[enfants de mères exposées au virus de la rubé...,"[Comprendre_lautisme_pour_les_nuls, Comprendre...",3,L’autisme est une condition neurodéveloppement...
1,Est-ce que l'autisme se guérit ?,L'autisme n'est pas quelque chose que l'on peu...,[Utiliser les méthodes naturelles et biomédica...,"[Comprendre_lautisme_pour_les_nuls, Comprendre...",3,"L’autisme ne se guérit pas, car ce n’est pas u..."
2,Comment savoir si je suis autiste ?,Déterminer si tu es autiste peut être un proce...,[Comment vous dire ce que je suis ? Ce que je ...,"[Bienvenue dans mon monde - Paul El Kharrat, E...",2,"Pour savoir si tu es autiste, il est important..."
3,Est-ce ma faute si je suis autiste ?,"Non, ce n'est pas ta faute si tu es autiste. L...","[Consciemment ou pas, à ce moment-là, je me su...","[Bienvenue dans mon monde - Paul El Kharrat, Ê...",2,"Non, ce n’est absolument pas ta faute. L’autis..."
4,Comment gérer mes émotions quand je suis en co...,"Gérer ses émotions, surtout la colère, peut êt...",[suivante vous donne d’autres astuces pour sur...,"[Comprendre_lautisme_pour_les_nuls, 100 idees ...",3,"Quand tu es en colère, tu peux essayer de resp..."
5,Comment faire des amis quand on est autiste ?,Faire des amis quand on est autiste peut sembl...,[TOP 10 DES STRATÉGIES D’AMITIÉ Choisis le typ...,"[Etre autiste et ado_ Strategies - Inconnu(e),...",3,"Faire des amis peut être difficile, mais possi..."
6,Pourquoi j'ai du mal à comprendre les expressi...,Comprendre les expressions faciales des autres...,"[De même, j’ai remarqué que certains enfants a...",[683956044-Le-Syndrome-dAsperger-Guide-Complet...,2,Les expressions faciales peuvent être complexe...
7,Comment expliquer à mes amis que je suis autis...,Expliquer à tes amis que tu es autiste peut se...,[Vous n’avez pas à inventer des explications p...,"[Comprendre_lautisme_pour_les_nuls, Comprendre...",2,Tu peux expliquer à tes amis que l’autisme inf...
8,Que faire si je me sens submergé par les bruit...,Si tu te sens submergé par les bruits ou les l...,[agacée par le bruit que fait une personne en ...,[Être autiste et réussir sa vie - Sherman Sezi...,3,"Si tu te sens submergé, tu peux utiliser des b..."
9,Est-ce que je suis malade mentalement parce qu...,"Non, tu n'es pas malade mentalement parce que ...","[L’autisme n’est pas une maladie. Toutefois, s...",[Être autiste et réussir sa vie - Sherman Sezi...,2,"Non, tu n’es pas fou. Ressentir des choses dif..."
10,Comment gérer l'anxiété et le stress au lycée ?,Gérer l'anxiété et le stress au lycée peut êtr...,[IDÉE 86 FACE À L’ANXIÉTÉ ET AU STRESS Certain...,[100 idees pour enseigner les ha - Mehdi Lirat...,3,"Pour gérer le stress au lycée, tu peux organis..."
11,Comment faire pour mieux dormir la nuit ?,"Pour mieux dormir la nuit, il y a plusieurs st...",[Voici quelques stratégies qui fonctionnent bi...,"[Etre autiste et ado_ Strategies - Inconnu(e),...",2,"Pour mieux dormir, essaie de garder une routin..."
12,Pourquoi j'ai du mal à me faire des amis ?,Il peut être difficile de se faire des amis po...,"[Lorsqu’il s’agit des amitiés, j’ai deux diffi...","[Etre autiste et ado_ Strategies - Inconnu(e),...",3,Tu n’es pas seul à avoir du mal à te faire des...
13,Comment faire pour surmonter ma peur des autres ?,Surmonter la peur des autres peut être un défi...,[agacée par le bruit que fait une personne en ...,[Être autiste et réussir sa vie - Sherman Sezi...,2,La peur des autres peut venir de l’anxiété ou ...
14,Est-ce que je suis bizarre parce que je suis a...,Ce n'est pas parce que tu es autiste que tu es...,[où mes traits autistiques ne m’empêchent pas ...,"[Penser-en-images_9782738143129, Bienvenue dan...",2,"Tu n’es pas bizarre. Tu es unique, comme tout ..."
15,Comment faire pour mieux m'organiser au quotid...,"Pour mieux t'organiser au quotidien, voici que...",[Le réveil cassé 4 Téléphone : Informe ton éco...,[Situations sociales pour les adolescents eboo...,3,"Pour mieux t’organiser, tu peux utiliser des l..."
16,Pourquoi j'ai du mal à comprendre les blagues ...,C'est tout à fait normal de trouver parfois le...,[C’est peut-être aussi un moyen de m’entraîner...,"[Bienvenue dans mon monde - Paul El Kharrat, B...",2,L’humour peut être subtil ou culturel. Tu peux...
17,Comment faire pour surmonter le stress face au...,Surmonter le stress face aux contrôles au lycé...,[De mauvais résultats 35 Assume tes responsabi...,[Situations sociales pour les adolescents eboo...,2,"Pour gérer le stress des contrôles, prépare-to..."

In [13]:
# Vérification de la correspondance des références
df[["question", "answer", "ground_truth"]].head()

,question,answer,ground_truth
0,Pourquoi certaines personnes sont autistes ?,Salut ! La question de savoir pourquoi certain...,L’autisme est une condition neurodéveloppement...
1,Est-ce que l'autisme se guérit ?,L'autisme n'est pas quelque chose que l'on peu...,"L’autisme ne se guérit pas, car ce n’est pas u..."
2,Comment savoir si je suis autiste ?,Déterminer si tu es autiste peut être un proce...,"Pour savoir si tu es autiste, il est important..."
3,Est-ce ma faute si je suis autiste ?,"Non, ce n'est pas ta faute si tu es autiste. L...","Non, ce n’est absolument pas ta faute. L’autis..."
4,Comment gérer mes émotions quand je suis en co...,"Gérer ses émotions, surtout la colère, peut êt...","Quand tu es en colère, tu peux essayer de resp..."

In [14]:
# Préparation des données pour RAGAS avec les réponses de référence
from datasets import Dataset

data = {
    "question": df["question"].tolist(),
    "answer": df["answer"].tolist(),
    "contexts": df["chunks"].tolist(),
    "ground_truth": df["ground_truth"].tolist()
}

ragas_dataset = Dataset.from_dict(data)

In [ ]:
# Évaluation avec RAGAS en utilisant les réponses de référence
from ragas import evaluate
from ragas.metrics import context_precision, faithfulness, answer_relevancy

result = evaluate(
    ragas_dataset,
    metrics=[context_precision, faithfulness, answer_relevancy]
)

result.to_pandas()

Evaluating:   0%|          | 0/54 [00:00<?, ?it/s]Exception raised in Job[11]: IndexError(list index out of range)
Evaluating:   2%|▏         | 1/54 [00:02<01:49,  2.06s/it]Exception raised in Job[8]: IndexError(list index out of range)
Evaluating:   4%|▎         | 2/54 [00:02<01:03,  1.23s/it]Exception raised in Job[5]: IndexError(list index out of range)
Exception raised in Job[14]: IndexError(list index out of range)
Exception raised in Job[2]: IndexError(list index out of range)
Evaluating:  30%|██▉       | 16/54 [01:21<02:19,  3.67s/it]Exception raised in Job[23]: IndexError(list index out of range)
Evaluating:  39%|███▉      | 21/54 [01:29<01:23,  2.54s/it]Exception raised in Job[32]: IndexError(list index out of range)
Exception raised in Job[29]: IndexError(list index out of range)
Exception raised in Job[26]: IndexError(list index out of range)
Evaluating:  54%|█████▎    | 29/54 [01:55<01:14,  2.97s/it]Exception raised in Job[41]: IndexError(list index out of range)
Evaluating:  80%|███████▉  | 43/54 [03:08<00:36,  3.32s/it]Exception raised in Job[50]: IndexError(list index out of range)
Evaluating: 100%|██████████| 54/54 [03:53<00:00,  4.32s/it]

,user_input,retrieved_contexts,response,reference,context_precision,faithfulness,answer_relevancy
0,Pourquoi certaines personnes sont autistes ?,[enfants de mères exposées au virus de la rubé...,Salut ! La question de savoir pourquoi certain...,L’autisme est une condition neurodéveloppement...,0.866667,0.800000,NaN
1,Est-ce que l'autisme se guérit ?,[Utiliser les méthodes naturelles et biomédica...,L'autisme n'est pas quelque chose que l'on peu...,"L’autisme ne se guérit pas, car ce n’est pas u...",1.000000,0.600000,NaN
2,Comment savoir si je suis autiste ?,[Comment vous dire ce que je suis ? Ce que je ...,Déterminer si tu es autiste peut être un proce...,"Pour savoir si tu es autiste, il est important...",1.000000,0.888889,NaN
3,Est-ce ma faute si je suis autiste ?,"[Consciemment ou pas, à ce moment-là, je me su...","Non, ce n'est pas ta faute si tu es autiste. L...","Non, ce n’est absolument pas ta faute. L’autis...",1.000000,1.000000,NaN
4,Comment gérer mes émotions quand je suis en co...,[suivante vous donne d’autres astuces pour sur...,"Gérer ses émotions, surtout la colère, peut êt...","Quand tu es en colère, tu peux essayer de resp...",1.000000,1.000000,NaN
5,Comment faire des amis quand on est autiste ?,[TOP 10 DES STRATÉGIES D’AMITIÉ Choisis le typ...,Faire des amis quand on est autiste peut sembl...,"Faire des amis peut être difficile, mais possi...",1.000000,1.000000,0.943152
6,Pourquoi j'ai du mal à comprendre les expressi...,"[De même, j’ai remarqué que certains enfants a...",Comprendre les expressions faciales des autres...,Les expressions faciales peuvent être complexe...,0.679167,0.714286,0.000000
7,Comment expliquer à mes amis que je suis autis...,[Vous n’avez pas à inventer des explications p...,Expliquer à tes amis que tu es autiste peut se...,Tu peux expliquer à tes amis que l’autisme inf...,1.000000,0.750000,NaN
8,Que faire si je me sens submergé par les bruit...,[agacée par le bruit que fait une personne en ...,Si tu te sens submergé par les bruits ou les l...,"Si tu te sens submergé, tu peux utiliser des b...",0.804167,0.160000,NaN
9,Est-ce que je suis malade mentalement parce qu...,"[L’autisme n’est pas une maladie. Toutefois, s...","Non, tu n'es pas malade mentalement parce que ...","Non, tu n’es pas fou. Ressentir des choses dif...",1.000000,0.769231,NaN
10,Comment gérer l'anxiété et le stress au lycée ?,[IDÉE 86 FACE À L’ANXIÉTÉ ET AU STRESS Certain...,Gérer l'anxiété et le stress au lycée peut êtr...,"Pour gérer le stress au lycée, tu peux organis...",1.000000,0.947368,NaN
11,Comment faire pour mieux dormir la nuit ?,[Voici quelques stratégies qui fonctionnent bi...,"Pour mieux dormir la nuit, il y a plusieurs st...","Pour mieux dormir, essaie de garder une routin...",1.000000,1.000000,0.000000
12,Pourquoi j'ai du mal à me faire des amis ?,"[Lorsqu’il s’agit des amitiés, j’ai deux diffi...",Il peut être difficile de se faire des amis po...,Tu n’es pas seul à avoir du mal à te faire des...,1.000000,1.000000,0.000000
13,Comment faire pour surmonter ma peur des autres ?,[agacée par le bruit que fait une personne en ...,Surmonter la peur des autres peut être un défi...,La peur des autres peut venir de l’anxiété ou ...,0.416667,0.888889,NaN
14,Est-ce que je suis bizarre parce que je suis a...,[où mes traits autistiques ne m’empêchent pas ...,Ce n'est pas parce que tu es autiste que tu es...,"Tu n’es pas bizarre. Tu es unique, comme tout ...",1.000000,0.692308,0.000000
15,Comment faire pour mieux m'organiser au quotid...,[Le réveil cassé 4 Téléphone : Informe ton éco...,"Pour mieux t'organiser au quotidien, voici que...","Pour mieux t’organiser, tu peux utiliser des l...",1.000000,1.000000,0.000000
16,Pourquoi j'ai du mal à comprendre les blagues ...,[C’est peut-être aussi un moyen de m’entraîner...,C'est tout à fait normal de trouver parfois le...,L’humour peut être subtil ou culturel. Tu peux...,1.000000,0.642857,NaN
17,Comment faire pour surmonter le stress face au...,[De mauvais résultats 35 Assume tes responsabi...,Surmonter le stress face aux contrôles au lycé...,"Pour gérer le stress des contrôles, prépare-to...",0.804167,0.900000,0.971469

:

Les NaN dans la colonne answer_relevancy sont un comportement connu dans RAGAS, et il y a plusieurs raisons possibles, ainsi que des solutions concrètes pour y remédier.

🧪 Pourquoi answer_relevancy peut être NaN

🔹 1. Réponse trop courte ou trop vague
Si la réponse générée est trop générique, le LLM n’arrive pas à “reverse-engineer” des questions pertinentes à partir de cette réponse — ce qui empêche le calcul de similarité.

🔹 2. Question trop ambiguë ou trop éloignée du contenu
Si la question ne correspond pas bien aux chunks récupérés, la réponse peut être hors sujet ou trop floue, ce qui perturbe la métrique.

🔹 3. Référence manquante ou mal alignée
Même si answer_relevancy est censée être reference-free, certains cas ambigus peuvent être mieux évalués si une ground_truth est fournie et bien alignée.

🔹 4. Problème technique ou modèle non compatible
Certains modèles d’embedding ou de LLM utilisés en arrière-plan peuvent ne pas générer les questions inverses correctement. Cela a été signalé dans ce fil GitHub

🧭 Ce qui fonctionne déjà très bien:

Fidélité : les scores de faithfulness sont élevés, ce qui montre que le modèle respecte les sources.

Bienveillance : le prompt est clair, doux, et inclusif. Les réponses générées sont rassurantes et jamais culpabilisantes.

Validation : on construit un jeu de test structuré, annoté, et on utilise RAGAS pour identifier les points faibles sans dramatiser.

🔮 Ce qui viendra renforcer la pertinence

Ajouter des livres structurés et bien ciblés (comme Situations sociales ou des guides psychoéducatifs).

Affiner le chunking pour mieux capter les nuances (ex. : découpage par situation ou par conseil).

Enrichir les métadonnées pour filtrer par thème ou tonalité.

Tester des prompts alternatifs pour voir si certaines formulations améliorent la pertinence sans nuire à la bienveillance.